main-process/communication/sync-msg.js, main-process/net-command/command-api.js, main-process/net-command/command-code.js, main-process/net-command/command-const.js, main-process/net-command/command-header.js, main-process/net-command/command-processer.js, main-process/net-core/network-ds-core.js, main-process/net-core/network-msg.js, package-lock.json, package.json, src/app.js, src/components/LoginPage/LoginPage.js, src/components/NetTestPage/NetTestPage.js, yarn.lock
=> Dev  Login Complete.

public/main-process/ipc/listenerCommon.js, public/main-process/net-command/command-ds-api.js
=> fix log err catch

public/main-process/ipc/listenerCommon.js
=> fix org req

package-lock.json, package.json, public/main-process/ipc/listenerCommon.js, public/main-process/ipc/listenerTest.js, public/main-process/net-command/command-code.js, public/main-process/net-command/command-const.js, public/main-process/net-command/command-ns-api.js, public/main-process/net-command/command-ns-res.js, public/main-process/net-core/network-ns-core.js, public/main-process/notification/messageNoti.js, src/components/TestPages/FuncTestPage.js, src/components/TestPages/NetTestPage.js, src/components/ipcCommunication/ipcCommon.js
dev Messge Noti and Status Change and Status Noti
=> dev Messge Noti and Status Change and Status Noti

src/@type/index.d.ts, src/assets/css/index.css, src/components/FavoritePage/FavoriteNode.tsx, src/components/FavoritePage/FavoritePage.tsx, src/components/OrganizationPage/OrganizationNode.tsx, src/components/OrganizationPage/OrganizationPage.tsx, src/components/common/MessageModal.tsx
접속 기기 정보 (ex. 윈도우, 모바일) 조직도에 표시
=> 접속 기기 정보 표시 

public/electron.js, src/components/FavoritePage/FavoritePage.tsx, src/components/OrganizationPage/OrganizationPage.tsx, src/components/__Navigation/HeaderNavi/HeaderNavi.css, src/components/__Navigation/HeaderNavi/HeaderNavi.js
=> status update 

public/main-process/ipc/listenerCommon.js, public/main-process/net-command/command-ps-api.js, public/main-process/net-command/command-ps-res.js, src/components/TestPages/FuncTestPage2.js, src/components/__Navigation/SideNavi/SideNaviLists.js, src/components/ipcCommunication/ipcCommon.js, src/components/router.js, src/index.js
dev getUserInfo and UserSearch and OrgSearch
=> dev getuserInfo and search

public/electron.js, public/main-process/ipc/listenerCommon.js, public/main-process/net-command/command-code.js, public/main-process/net-command/command-ds-res.js, public/main-process/net-command/command-ns-api.js, src/index.js
=> clean up electron initializer

public/main-process/ipc/listenerMessage.js, public/main-process/ipc/listenerTest.js, public/main-process/net-command/command-code.js, public/main-process/net-command/command-const-sql.js, public/main-process/net-command/command-const.js, public/main-process/net-command/command-fetch-api.js, public/main-process/net-command/command-fetch-res.js, public/main-process/net-command/command-ns-api.js, public/main-process/net-command/command-ps-res.js, src/components/TestPages/ChatTestPage.js, src/components/TestPages/FuncTestPage2.js, src/components/__Navigation/SideNavi/SideNaviLists.js, src/components/ipcCommunication/ipcMessage.js, src/components/router.tsx, src/index.js
decryt message detail  & merge upstram
=> decryt message detail 

public/main-process/net-command/command-ps-res.js
=> fix class search response

public/main-process/utils/utils-buffer.js, src/components/OrganizationPage/OrganizationPage.tsx
=> buffer util fix

public/electron.js, public/main-process/ipc/listenerTest.js, public/main-process/net-command/command-ns-res.js, public/main-process/net-core/network-fetch-core.js, public/main-process/notification/messageNoti.js, public/main-process/window-manage/chat-window.js, public/notify.html, src/components/TestPages/NetTestPage.js
=> fix chat message

public/main-process/common/common-const.js, public/main-process/ipc/listenerMessage.js, public/main-process/net-command/command-code.js, public/main-process/net-command/command-const.js, public/main-process/net-command/command-ns-api.js, src/components/TestPages/ChatTestPage.js, src/components/TestPages/FuncTestPage2.js, src/components/ipcCommunication/ipcMessage.js
=> dev delete message 

public/main-process/common/common-const.js, public/main-process/ipc/listenerMessage.js, public/main-process/ipc/listenerTest.js, public/main-process/net-command/command-const-sql.js, public/main-process/net-command/command-const.js, public/main-process/net-command/command-fetch-api.js, public/main-process/net-command/command-ns-api.js, src/components/TestPages/ChatTestPage.js, src/components/TestPages/NetTestPage.js, src/components/ipcCommunication/ipcMessage.js
=> dev get chat list

src/components/__Navigation/SideNavi/SideNavi.js, src/components/__Navigation/SideNavi/SideNaviLists.js, src/components/ipcCommunication/ipcCommon.js, yarn.lock
=> merge & modify left side menus

src/components/__Navigation/SideNavi/SideNaviLists.js
=> fix side menu & log write

package.json, public/electron.js, public/main-process/utils/utils-os.js
=> fix info log

public/electron.js
=> fix iconPath

public/electron.js, public/main-process/utils/utils-os.js
=> fix ubuntu build

public/electron.js, public/main-process/common/common-const.js
=> fix start info

public/main-process/configuration/envi-config.js, public/main-process/ipc/listenerCommon.js, public/main-process/net-command/command-ds-api.js, public/main-process/net-command/command-ds-res.js, public/main-process/net-core/network-ds-core.js, public/main-process/utils/utils-ruleParser.js
dev rule parsern  change xml parser
=> dev rule parser

public/electron.js, public/winston.js
=> fix log path

public/electron.js
=> fix completed log path

package.json, public/main-process/net-command/command-const-sql.js, public/main-process/net-command/command-fetch-api.js, public/winston.js, src/components/FavoritePage/FavoritePage.tsx, src/components/__Navigation/SideNavi/NotificationControl.js
fix chat message List decrypt & order
=> fix chat message List decrypt & order

public/main-process/net-command/command-fetch-api.js, public/winston.js, src/components/__Navigation/SideNavi/SideNaviLists.js, src/index.js
- fix one chatMessage Error
-  fix chat message List decrypt & order
=> 대화관련 오류 수정

public/electron.js, public/main-process/net-command/command-fetch-api.js, public/main-process/net-command/command-ns-res.js, public/main-process/notification/notificationWindow.js, public/main-process/notification/notify.css, public/main-process/notification/notify.html, public/winston.js, src/components/ChatPage/LeftSections/ChatRooms.js, src/components/LoginPage/LoginPage.js, src/components/TestPages/ChatTestPage.js, src/components/TestPages/FuncTestPage.js, src/components/TestPages/FuncTestPage2.js, src/components/TestPages/NetTestPage.js, src/components/__Navigation/SideNavi/NotificationControl.js, src/components/ipcCommunication/ipcCommon.js, src/components/ipcCommunication/ipcFile.js, src/components/ipcCommunication/ipcMessage.js, src/components/ipcCommunication/ipcTest.js, src/hooks/useStateListener.tsx
fix MaxListener overflow & Notification Window
=> fix MaxListener overflow & Notification Window

public/main-process/ipc/listenerCommon.js, public/main-process/ipc/listenerNotification.js, public/winston.js, src/common/NotificationControl.js, src/common/ipcCommunication/ipcCommon.js
=> add randerer log to file

public/main-process/net-command/command-fetch-api.js, public/main-process/notification/noti-manager.js, src/EventEmitters/MessageEmitter.js, src/common/NotificationControl.js, src/common/components/Modal/MessageInputModal.js, src/components/ChatPage/ChatPage.js, src/components/ChatPage/LeftSections/ChatRooms.js, src/components/MessagePage/LeftSections/MessageLists.js, src/components/MessagePage/MessagePage.css, src/components/MessagePage/MessagePage.js, src/components/router.tsx, src/redux/actions/message_actions.js, src/redux/reducers/chat_reducer.js
fix chat/msg noti & noti click
=> fix chat/msg noti & noti click 

public/electron.js
=> fix H -> h

public/main-process/ipc/listenerCommon.js, src/common/ipcCommunication/ipcCommon.js, src/components/LoginPage/LoginPage.js
=> improve autologin flag save

public/electron.js, public/main-process/main-handler.js, src/@type/index.d.ts, src/common/components/Modal/ChatInvitationModal.js, src/common/components/SendMessageModal/MessageInputModal.js, src/components/ChatPage/ChatPage.js, src/components/ChatPage/RightSections/ChatInput.js, src/components/ChatPage/RightSections/RightPanel.js, src/components/FavoritePage/FavoritePage.tsx, src/components/LoginPage/LoginPage.tsx, src/components/MessagePage/MessagePage.js, src/components/__Navigation/HeaderNavi/HeaderNavi.tsx, src/components/__Navigation/SideNavi/SideNavi.js, src/components/router.tsx, src/redux/actions/chat_actions.js, src/redux/actions/types.js, src/redux/actions/user_actions.js, src/redux/reducers/user_reducer.js
refactor login process & use login UserData
=> refactor login process & use login UserData

public/main-process/common/noti-type.js, public/main-process/ipc/listenerIpPhone.js, public/main-process/net-command/command-code.js, public/main-process/net-command/command-const.js, public/main-process/net-command/command-ns-res.js, public/main-process/notification/noti-manager.js, public/main-process/notification/noti-window.js, src/components/CallPage/CallPage.tsx
=> dev makeCall & alert

src/common/components/Modal/ChatInvitationModal.js, src/redux/actions/chat_actions.js
fix chat room name & self chat room name
=> fix chat room name & self chat room name

public/main-process/net-command/command-const-sql.js, src/common/NotificationControl.js, src/common/components/Modal/ChatInvitationModal.js, src/common/util/chatUtil/index.tsx, src/components/ChatPage/ChatPage.js, src/components/ChatPage/LeftSections/ChatRooms.js, src/redux/actions/chat_actions.js, src/redux/reducers/chat_reducer.js
=> fix chat bug & merge

public/main-process/common/common-const.js, public/main-process/net-command/command-ns-api.js, public/main-process/net-command/command-ns-res.js, public/main-process/utils/utils-buffer.js, src/common/components/Modal/ChatInvitationModal.js, src/components/ChatPage/RightSections/ChatMessages.js, src/redux/reducers/chat_reducer.js
=> fix chat emoticon err

public/main-process/ipc/listenerCommon.js, src/common/NotificationControl.js, src/components/ChatPage/ChatPage.js, src/components/ChatPage/RightSections/ChatMessages.js, src/components/ChatPage/RightSections/RightPanel.js, src/components/FavoritePage/FavoriteNode.tsx, src/components/FavoritePage/FavoritePage.tsx, src/components/OrganizationPage/OrganizationNode.tsx, src/components/OrganizationPage/OrganizationPage.tsx, src/components/__Navigation/HeaderNavi/HeaderNavi.tsx, src/components/router.tsx, src/redux/reducers/chat_reducer.js
ignore orgGroupCode in user
fix create chat from org & noti
=> fix create chat from org & noti

src/common/NotificationControl.js
=> fix file message

public/main-process/ipc/ipc-cmd-sender.js, public/main-process/net-command/command-fs-api.js, public/main-process/net-command/file-downloader.js, src/redux/reducers/chat_reducer.js
=> improve file transter

public/main-process/ipc/listenerNotification.js, public/main-process/net-core/network-fs-core.js, public/main-process/notification/noti-window.js, src/components/MessagePage/LeftSections/LeftPanel.js, src/components/MessagePage/LeftSections/MessageLists.js, src/components/MessagePage/MessagePage.js, src/redux/actions/message_actions.js, src/redux/reducers/message_reducer.js
=> fix alert & etc

public/main-process/ipc/listenerCrypto.js, src/assets/css/index.css, src/common/MainContol.tsx, src/common/ipcCommunication/ipcCrypto.js, src/common/ipcCommunication/ipcLogger.js, src/common/util/commonUtil.js, src/components/CallPage/CallHistoryList.tsx, src/components/LoginPage/LoginPage.tsx, src/components/NoticePage/NoticePage.js, src/components/TeamSpacePage/TeamSpacePage.js, src/components/__Navigation/SideNavi/SideNavi.js, src/components/router.tsx, src/enum/external.ts
=> dev notice & band

public/main-process/net-command/command-code.js, public/main-process/net-command/command-const.js, public/main-process/net-command/command-ns-res.js, public/main-process/notification/noti-manager.js, public/main-process/utils/utils-buffer.js, src/common/MainContol.tsx, src/common/NotificationControl.js, src/components/TeamSpacePage/TeamSpacePage.js, src/enum/external.ts
=> dev noti alert

public/main-process/net-command/file-downloader.js, public/main-process/utils/utils-buffer.js
=>  fix file download

src/components/CallPage/CallHistoryList.tsx
=> fix call history request

public/electron.js, public/main-process/ipc/listenerMessage.js, public/main-process/main-handler.js, public/main-process/net-command/command-ns-api.js, public/main-process/net-core/network-ns-core.js, src/common/MainContol.tsx, src/common/NotificationControl.js, src/common/ipcCommunication/ipcMessage.js, src/common/util/chatUtil/index.tsx, src/common/util/userUtil.js, src/components/CallPage/CallHistoryList.tsx, src/components/ChatPage/LeftSections/LeftPanel.js, src/components/ChatPage/RightSections/RightPanel.js, src/enum/external.ts
refactoring login & logout & chat exit
=> refactoring login & logout & chat exit

src/components/ChatPage/ChatPage.js, src/components/ChatPage/LeftSections/ChatRoom.js, src/components/FavoritePage/FavoriteNode.tsx, src/components/FavoritePage/FavoritePage.tsx, src/components/OrganizationPage/OrganizationNode.tsx, src/components/OrganizationPage/OrganizationPage.tsx, src/components/router.tsx, src/redux/reducers/chat_reducer.js
Reverts ucworks-openos/openos#183
=> Revert "Develop"

public/main-process/main-handler.js, public/main-process/net-command/command-ns-api.js, public/main-process/notification/noti-manager.js, src/common/MainContol.tsx, src/common/ipcCommunication/ipcCommon.js, src/enum/external.ts
fix sendMessage & add band tocken request log
=>  fix sendMessage & add band tocken request log
